Add SQLCompiler to compiler
Assign SQLCompiler from the compiler object since Django assumes there
will be a SQLCompiler class within the backend compiler.  This should
prevent errors along the lines of:
    AttributeError: 'module' object has no attribute 'SQLCompiler'